# Generated by Django 4.2.13 on 2024-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('posts', models.ManyToManyField(related_name='authors', to='blogstart.post')),
            ],
        ),
    ]
