# Generated by Django 4.2.13 on 2024-07-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogstart', '0003_remove_author_posts_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogstart.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blogstart.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Post_Author',
        ),
    ]
